# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_types

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Amount(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Amount()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAmount(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Amount
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Amount
    def Number(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Amount
    def Currency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AmountStart(builder):
    builder.StartObject(2)

def Start(builder):
    AmountStart(builder)

def AmountAddNumber(builder, number):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(number), 0)

def AddNumber(builder, number):
    AmountAddNumber(builder, number)

def AmountAddCurrency(builder, currency):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(currency), 0)

def AddCurrency(builder, currency):
    AmountAddCurrency(builder, currency)

def AmountEnd(builder):
    return builder.EndObject()

def End(builder):
    return AmountEnd(builder)
