# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_types

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Close(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Close()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClose(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Close
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Close
    def Account(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CloseStart(builder):
    builder.StartObject(1)

def Start(builder):
    CloseStart(builder)

def CloseAddAccount(builder, account):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(account), 0)

def AddAccount(builder, account):
    CloseAddAccount(builder, account)

def CloseEnd(builder):
    return builder.EndObject()

def End(builder):
    return CloseEnd(builder)
