# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_types

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CostSpec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CostSpec()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCostSpec(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CostSpec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CostSpec
    def NumberPer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSpec
    def NumberTotal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSpec
    def Currency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSpec
    def Date(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from beancount_data.fbs.data_types.Date import Date
            obj = Date()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CostSpec
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSpec
    def Merge(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def CostSpecStart(builder):
    builder.StartObject(6)

def Start(builder):
    CostSpecStart(builder)

def CostSpecAddNumberPer(builder, numberPer):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(numberPer), 0)

def AddNumberPer(builder, numberPer):
    CostSpecAddNumberPer(builder, numberPer)

def CostSpecAddNumberTotal(builder, numberTotal):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(numberTotal), 0)

def AddNumberTotal(builder, numberTotal):
    CostSpecAddNumberTotal(builder, numberTotal)

def CostSpecAddCurrency(builder, currency):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(currency), 0)

def AddCurrency(builder, currency):
    CostSpecAddCurrency(builder, currency)

def CostSpecAddDate(builder, date):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(date), 0)

def AddDate(builder, date):
    CostSpecAddDate(builder, date)

def CostSpecAddLabel(builder, label):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0)

def AddLabel(builder, label):
    CostSpecAddLabel(builder, label)

def CostSpecAddMerge(builder, merge):
    builder.PrependBoolSlot(5, merge, 0)

def AddMerge(builder, merge):
    CostSpecAddMerge(builder, merge)

def CostSpecEnd(builder):
    return builder.EndObject()

def End(builder):
    return CostSpecEnd(builder)
