# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_types

class EntryPayload(object):
    NONE = 0
    Open = 1
    Close = 2
    Commodity = 3
    Pad = 4
    Balance = 5
    Transaction = 6
    Note = 7
    Event = 8
    Document = 9
    Custom = 10
